.Dd $Mdocdate: October 08 2024 $
.Dt HEREDOC 7
.Os
.Sh NAME
.Nm heredoc
.Nd write content
.Sh SYNOPSIS
.Bd -literal
module:heredoc
heredoc{
	[content]
}
.Ed
.Sh DESCRIPTION
The
.Nm
module reads the
.Dq heredoc
variable content and writes it to the
.Xr automate 1
output.
.Sh EXIT STATUS
.Ex -std
.Sh EXAMPLES
To create a hello world:
.Bd -literal -offset indent
#!/bin/automate -s default,c
program:hello
hello.c{
	output:$3
	module:heredoc
	heredoc{
		#include <stdio.h>
		int
		main(void) {
			puts("Hello, World!");
			return 0;
		}
	}
}
.Ed
.Sh SEE ALSO
.Xr automate 1 ,
.Xr venus-conf 5
