.Dd $Mdocdate: February 23 2025 $
.Dt AUTOMATE 1
.Os
.Sh NAME
.Nm automate
.Nd redo declarative frontend
.Sh SYNOPSIS
.Nm
.Op Fl s Ar set
.Ar file
.Ar rule
.Ar strip
.Ar tmp
.Sh DESCRIPTION
The
.Nm
utility processes the specified
.Ar rule
from the specified
.Ar file
encoded in
.Xr automate 5
format.
.Pp
The execution follows the following steps:
.Bl -enum -offset indent -compact
.It
Execute
.Xr redo-ifchange 1
for
.Sq Ar file Ns .transform .
.It
Select an
.Em automate block
matching
.Ar rule
in
.Sq Ar file Ns .transform .
.It
Import the env files for the specified
.Ar set Ns s .
.It
Execute
.Xr automate-cmd 1
for the selected block.
.El
.Pp
If the specified
.Ar file
name starts with
.Dq default.
the selection is determined as if
.Xr redo-whichdo 1
were executed for the specified
.Ar rule ;
Otherwise, the given
.Ar file
itself is interpreted as an
.Em automate block .
.Pp
The following keys are injected in the selected block:
.Bl -tag -offset indent -width X -compact
.It 1
As
.Ar rule .
.It 2
As
.Ar strip .
.It 3
As
.Ar tmp .
.El
.Pp
The injected keys serve the same purpose as those provided by
.Xr redo 1 ,
for the
.Nm
utility is intended to be executed via
.Xr automate-do 1 .
.Ss TRANSFORM
The transform concatenates the specified
.Ar set Ns s
and
.Ar file ,
then executes
.Xr automate-cmd 1
for each
.Em transform block .
.Pp
A
.Em transform block
is an
.Em automate block
named
.Dq transform .
The content is processed outside-in. When a
.Em transform block
is found, its entire content is passed to
.Xr automate-cmd 1 .
The command's output is captured verbatim and replaces the
original block without further interpretation.
.Pp
For example:
.Bd -literal -offset indent
# Before
target-arch-options{
	transform{
		transform:now-I-am-just-a-normal-entry
		command:uname -m
	}
	generic
}
# After
target-arch-options{
	x86_64
	generic
}
.Ed
.Pp
This process is intended to programmatically generate static content.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl s Ar set Ns s
Include sets from the comma-separated
.Pq Sq \&,
list of
.Ar set Ns s .
.El
.Sh ENVIRONMENT
.Bl -tag -width XXXXXXXXXXXXXXXXXXXX
.It Ev AUTOMATE_ETC_DIR
The directories where
.Nm
configuration data is found.
.It Ev AUTOMATE_LIBEXEC_DIR
The directories where
.Nm
modules and binaries are found.
.El
.Sh FILES
.Bl -tag -width XXXXXXXXXXXXXXXXXXXXXXX -compact
.It Pa Ev AUTOMATE_ETC_DIR Ns /env
The global env directory.
.It Pa Ev AUTOMATE_ETC_DIR Ns /sets
The global sets directory.
.El
.Sh EXIT STATUS
.Ex -std
.Sh EXAMPLES
To write a hello world in C:
.Bd -literal -offset indent
#!/usr/bin/automate -s std-default,std-c
# including sets "std-default" and "std-c"
# file name:default.do
@program{
	hello
}
hello.c{
	%operating-system{
		transform{
			command:cat /etc/release
		}
	}
	module:std-heredoc
	heredoc{
		#include <stdio.h>
		int
		main(void)
		{
			puts("Hello, $:{%operating-system}");
			return 0;
		}
	}
}
.Ed
.Pp
To trigger the build:
.Dl $ automate-do
.Sh SEE ALSO
.Xr automate-cmd 1 ,
.Xr automate-do 1 ,
.Xr redo 1 ,
.Xr redo-ifchange 1 ,
.Xr automate 5 ,
.Xr automate-sets-std 7
