.Dd $Mdocdate: February 06 2025 $
.Dt SETS-STD 7
.Os
.Sh NAME
.Nm sets-std
.Nd standard sets
.Sh DESCRIPTION
The
.Nm
collections provide standardized configurations that simplify the creation of
.Xr automate 1
scripts.
.Sh SEE ALSO
.Xr automate 1 ,
.Xr automate-set-std-c 7 ,
.Xr automate-set-std-default 7
