.Dd $Mdocdate: February 06 2025 $
.Dt MODULES-STD 7
.Os
.Sh NAME
.Nm modules-std
.Nd standard modules
.Sh DESCRIPTION
The
.Nm
are official extensions that enhance the capabilities of
.Em automate blocks .
.Sh SEE ALSO
.Xr automate 1 ,
.Xr automate-cmd 1 ,
.Xr automate-module-std-cmd 7 ,
.Xr automate-module-std-glob 7 ,
.Xr automate-module-std-heredoc 7 ,
.Xr automate-module-std-map 7 ,
.Xr automate-module-std-pipe 7 ,
.Xr automate-module-std-rules 7 ,
.Xr automate-module-std-search 7
